name: build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      # Install requirements.txt that contains the dependencies
      - name: Install dependencies
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python get-pip.py
          pip3 install -r requirements.txt
          apt-get update -y && apt-get install python3-dev -y
      # Get location of customtkinter with pip show customtkinter and assign it to a variable
      - name: Get location of customtkinter
        id: customtkinter
        run: |
          echo "::set-output name=location::$(pip show customtkinter | grep Location | cut -d ' ' -f 2)"
      # Copy customtkinter to the current directory
      - name: Copy customtkinter
        run: |
          cp -r ${{ steps.customtkinter.outputs.location }}\/customtkinter .
      # Build using pyinstaller and the customtkinter folder
      - name: Build
        run: |
          pyinstaller --noconfirm --onedir --windowed --add-data "customtkinter:customtkinter" main.py
      # Upload the build as an artifact
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build/main/main